### ISSUE TITLE
conversion failed: could not save output document; OOo errorCode: 283

### ISSUE THREAD

**Issue by eriklight** [klxedu/blog#10]
> openOffice 文件转换异常，异常原因是转换文件为空，或文件不存在。
```
com.artofsolving.jodconverter.openoffice.connection.OpenOfficeException: conversion failed: could not save output document; OOo errorCode: 283
	at com.artofsolving.jodconverter.openoffice.converter.OpenOfficeDocumentConverter.loadAndExport(OpenOfficeDocumentConverter.java:142)
	at com.artofsolving.jodconverter.openoffice.converter.OpenOfficeDocumentConverter.convertInternal(OpenOfficeDocumentConverter.java:120)
	at com.artofsolving.jodconverter.openoffice.converter.AbstractOpenOfficeDocumentConverter.convert(AbstractOpenOfficeDocumentConverter.java:104)
```

**Comment by Chichi666** [comment]
解决办法是什么呢
